### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by vodenkaj** [vodenkaj/rdbcli#1]
### Main Commands
- [x] #2 
- [x] #4
- [x] #16

### Sub Commands
- [x] #5
- [x] #6

### Commands
- [x] #15

### Output Parsing
- [x] #7

### Status Line
- [x] #8
  - [x] Current database name.

### Loader Component
- [x] #9
  - [x] Attempts to connect to the database upon startup.
  - [x] Displays an error message if the connection fails.

### Error Logging
- [x] #10
